@startuml UC

usecase c as "Gérer ses chantiers"
usecase g as "Gérer ses artisans"
usecase a as "Affectation des artisans"
usecase p as "Calculer la paye des artisans"

actor Direction
actor RessourcesHumaines

'Pour aligner les 2 acteurs :
a -[hidden]-> g
p -[hidden]-> a

Direction -> c
Direction -> a

RessourcesHumaines -> p
RessourcesHumaines -> g

@enduml
